In [1]:
import pandas as pd

In [2]:
medical = pd.read_csv("동물약국 시군별 수(06-11 수정됨).csv", encoding="cp949")
funeral = pd.read_csv("동물장례식장 시군별 수(06-11 수정됨).csv", encoding="cp949")
shelter = pd.read_csv("동물보호센터 시군별 수(06-11 수정됨).csv", encoding="cp949")
pet_hospital = pd.read_csv("시군별_동물병원_동물수.csv")

In [8]:
pet1 = pet[['시_주소', '총 등록 누계']]
pet1.head()

  시_주소  총 등록 누계
0  고양시    74752
1  용인시    67345
2  수원시    75775
3  성남시    60467
4  화성시    50288

In [3]:
shelter.head()

  시_주소  정상
0  가평군   1
1  고양시   1
2  광명시   1
3  광주시   2
4  구리시   1

In [3]:
pet_hospital = pet_hospital.rename(columns={'시군' : '시_주소'})
pet_hospital = pet_hospital.drop(columns=['시군구'])
pet_hospital.head()

  시_주소  동물병원수  개등록 누계  고양이등록 누계  총 등록 누계     병원당_동물수
0  고양시    123   73953       799    74752  607.739837
1  용인시    122   66533       812    67345  552.008197
2  수원시    121   75009       766    75775  626.239669
3  성남시    117   59674       793    60467  516.811966
4  화성시     96   49820       468    50288  523.833333

In [10]:
pet_hospital2 = pet_hospital[['시_주소', '동물병원수']]
pet_hospital2.head()

  시_주소  동물병원수
0  고양시    123
1  용인시    122
2  수원시    121
3  성남시    117
4  화성시     96

In [11]:
medical2 = medical[['시_주소', '정상']]
medical2 = medical2.rename(columns={'정상' : '약국 수'})
medical2.head()

  시_주소   약국 수
0  가평군   11.0
1  고양시  337.0
2  과천시   17.0
3  광명시   89.0
4  광주시   99.0

In [12]:
shelter2 = shelter.rename(columns={'정상' : '보호소 수'})
shelter2.head()

  시_주소  보호소 수
0  가평군      1
1  고양시      1
2  광명시      1
3  광주시      2
4  구리시      1

In [13]:
funeral2 = funeral[['시_주소', '정상']]
funeral2 = funeral2.rename(columns={'정상' : '장례식장 수'})
funeral2.head()

   시_주소  장례식장 수
0   고양시     1.0
1   광주시     7.0
2   구리시     0.0
3   김포시     3.0
4  남양주시     3.0

In [18]:
result = pet_hospital.merge(
    medical2,
    on='시_주소',
    how='left'
)

result = result.merge(
    funeral2,
    on='시_주소',
    how='left'
)

result = result.merge(
    shelter2,
    on='시_주소',
    how='left'
)

result.head()

  시_주소  동물병원수  개등록 누계  고양이등록 누계  총 등록 누계     병원당_동물수   약국 수  장례식장 수  보호소 수
0  고양시    123   73953       799    74752  607.739837  337.0     1.0    1.0
1  용인시    122   66533       812    67345  552.008197  262.0     2.0    1.0
2  수원시    121   75009       766    75775  626.239669  348.0     NaN    1.0
3  성남시    117   59674       793    60467  516.811966  321.0     NaN    1.0
4  화성시     96   49820       468    50288  523.833333  254.0     3.0    NaN

In [20]:
result2 = result[['시_주소', '총 등록 누계', '동물병원수', '병원당_동물수', '약국 수', '보호소 수', '장례식장 수']]
result2.head()

  시_주소  총 등록 누계  동물병원수     병원당_동물수   약국 수  보호소 수  장례식장 수
0  고양시    74752    123  607.739837  337.0    1.0     1.0
1  용인시    67345    122  552.008197  262.0    1.0     2.0
2  수원시    75775    121  626.239669  348.0    1.0     NaN
3  성남시    60467    117  516.811966  321.0    1.0     NaN
4  화성시    50288     96  523.833333  254.0    NaN     3.0

In [22]:
result2 = result2.rename(columns={'총 등록 누계' : '등록동물 수', '병원당_동물수' : '병원당 동물 수'})
result2.head()

  시_주소  등록동물 수  동물병원수    병원당 동물 수   약국 수  보호소 수  장례식장 수
0  고양시   74752    123  607.739837  337.0    1.0     1.0
1  용인시   67345    122  552.008197  262.0    1.0     2.0
2  수원시   75775    121  626.239669  348.0    1.0     NaN
3  성남시   60467    117  516.811966  321.0    1.0     NaN
4  화성시   50288     96  523.833333  254.0    NaN     3.0

In [23]:
result2.to_csv(
    '경기 시군별 돌봄 인프라 비교.csv',
    index=False,
    encoding='utf-8-sig')

In [17]:
result = pet1.merge(
    pet_hospital2,
    on='시_주소',
    how='left'
)

result = result.merge(
    medical2,
    on='시_주소',
    how='left'
)

result = result.merge(
    funeral2,
    on='시_주소',
    how='left'
)

result = result.merge(
    shelter2,
    on='시_주소',
    how='left'
)

result.head()

  시_주소  총 등록 누계  동물병원수   약국 수  장례식장 수  보호소 수
0  고양시    74752    123  337.0     1.0    1.0
1  용인시    67345    122  262.0     2.0    1.0
2  수원시    75775    121  348.0     NaN    1.0
3  성남시    60467    117  321.0     NaN    1.0
4  화성시    50288     96  254.0     3.0    NaN

In [20]:
result = result.sort_values(
    by='총 등록 누계',
    ascending=False).reset_index(drop=True)

result.head(15)

    시_주소  총 등록 누계  동물병원수   약국 수  장례식장 수  보호소 수
0    수원시    75775    121  348.0     NaN    1.0
1    고양시    74752    123  337.0     1.0    1.0
2    용인시    67345    122  262.0     2.0    1.0
3    성남시    60467    117  321.0     NaN    1.0
4    부천시    56443     70  259.0     NaN    4.0
5   남양주시    51450     69  194.0     3.0    2.0
6    화성시    50288     96  254.0     3.0    NaN
7    안산시    48821     39  190.0     3.0    1.0
8    평택시    37657     59  145.0     NaN    1.0
9    안양시    37024     53  174.0     NaN    NaN
10   시흥시    36969     39  157.0     NaN    1.0
11   파주시    34447     53  112.0     0.0    NaN
12  의정부시    31233     34  154.0     NaN    NaN
13   김포시    31128     52  131.0     3.0    NaN
14   광주시    28852     38   99.0     7.0    2.0