In [1]:
import pandas as pd

In [2]:
# 지역화폐 행정동 소비
local_2023 = pd.read_csv(
    "지역화폐/2023데이터분석지역화폐행정동소비.csv",
    encoding="cp949"
)

local_2024 = pd.read_csv(
    "지역화폐/2024데이터분석지역화폐행정동소비.csv",
    encoding="cp949"
)

local_2025 = pd.read_csv(
    "지역화폐/2025데이터분석지역화폐행정동소비.csv",
    encoding="cp949"
)

In [3]:
local_2023.head()

     기준년월       행정동코드 중분류업종코드        매출금액  활성화비율
0  202301  4111156000      00  57305338.0  100.0
1  202301  4111156000      A0         0.0    0.0
2  202301  4111156000      B0         0.0    0.0
3  202301  4111156000      B1         0.0    0.0
4  202301  4111156000      B2         0.0    0.0

In [4]:
# 1. 3개 연도 데이터 병합
local = pd.concat(
    [local_2023, local_2024, local_2025],
    ignore_index=True
)

# 2. 기준년월을 숫자로 변환
local["기준년월"] = pd.to_numeric(
    local["기준년월"],
    errors="coerce"
)

# 3. 2023년 7월 ~ 2025년 6월 필터링
local = local[
    local["기준년월"].between(202307, 202506)
].copy()

# 4. 인덱스 정리
local = local.reset_index(drop=True)

local.head()

     기준년월       행정동코드 중분류업종코드  매출금액  활성화비율
0  202307  4117354000      F0   0.0    0.0
1  202307  4117354000      F2   0.0    0.0
2  202307  4117354000      G0   0.0    0.0
3  202307  4117354000      G1   0.0    0.0
4  202307  4117354000      H0   0.0    0.0

In [5]:
print("최소 기준년월:", local["기준년월"].min())
print("최대 기준년월:", local["기준년월"].max())
print("포함 월 개수:", local["기준년월"].nunique())
print("행 개수:", len(local))

최소 기준년월: 202307
최대 기준년월: 202506
포함 월 개수: 24
행 개수: 428289

In [6]:
# 매출금액을 숫자형으로 확실하게 변환
local["매출금액"] = pd.to_numeric(
    local["매출금액"],
    errors="coerce"
)

# 매출금액이 0보다 큰 행만 남기기
local_sales = local[
    local["매출금액"] > 0
].copy()

# 인덱스 정리
local_sales = local_sales.reset_index(drop=True)

print("제거 전 행 개수:", len(local))
print("제거 후 행 개수:", len(local_sales))
print("남은 0원 행:", (local_sales["매출금액"] == 0).sum())

local_sales.head()

제거 전 행 개수: 428289
제거 후 행 개수: 10397
남은 0원 행: 0

     기준년월       행정동코드 중분류업종코드         매출금액  활성화비율
0  202307  4117354600      00   33111507.0  100.0
1  202307  4117355000      00  163355562.0  100.0
2  202307  4117356000      00  159448665.0  100.0
3  202307  4117356600      00  137424925.0  100.0
4  202307  4117357000      00  131434484.0  100.0

In [7]:
local_sales = local_sales.drop(columns=["중분류업종코드"])

In [8]:
print("결측값:", local["매출금액"].isna().sum())
print("0원:", (local["매출금액"] == 0).sum())
print("음수:", (local["매출금액"] < 0).sum())
print("양수:", (local["매출금액"] > 0).sum())

결측값: 0
0원: 417892
음수: 0
양수: 10397

In [9]:
save_path = "지역화폐_행정동소비_202307_202506.csv"

local_sales.to_csv(
    save_path,
    index=False,
    encoding="utf-8-sig"
)

print("저장 경로:", save_path)
print("저장 행 개수:", len(local_sales))

저장 경로: 지역화폐_행정동소비_202307_202506.csv
저장 행 개수: 10397

In [10]:
local_sales = pd.read_csv(
    "지역화폐_행정동소비_202307_202506.csv",
    encoding="utf-8-sig"
)

local_live = pd.read_csv(
    "경기도_행정동별_주민등록인구_202307_202506_수정.csv",
    encoding="utf-8-sig"
)

local_move = pd.read_csv(
    "유동인구_월별_분석용.csv",
    encoding="utf-8-sig"
)

local_store = pd.read_csv(
    "행정동코드별 업종 개수.csv",
    encoding="cp949"
)

In [11]:
display(local_sales.head())
display(local_live.head())
display(local_move.head())
display(local_store.head())

     기준년월       행정동코드         매출금액  활성화비율
0  202307  4117354600   33111507.0  100.0
1  202307  4117355000  163355562.0  100.0
2  202307  4117356000  159448665.0  100.0
3  202307  4117356600  137424925.0  100.0
4  202307  4117357000  131434484.0  100.0

        행정동코드             행정구역    기준연월     총인구수
0  4111156000  경기도 수원시 장안구 파장동  202307  22480.0
1  4111156000  경기도 수원시 장안구 파장동  202308  22451.0
2  4111156000  경기도 수원시 장안구 파장동  202309  22410.0
3  4111156000  경기도 수원시 장안구 파장동  202310  23628.0
4  4111156000  경기도 수원시 장안구 파장동  202311  24542.0

     기준년월       행정동코드     월유동인구수
0  202307  4111156000  241011.94
1  202308  4111156000  241268.02
2  202309  4111156000  236580.40
3  202310  4111156000  268762.16
4  202311  4111156000  253510.66

   Unnamed: 0               업종명(종목명)  개수         행정동코드    년도
0      176110        미용실두발전문/미용실두발전문   1  1.154561e+09  2025
1      176113  기타교육.교습.학원/기타교육.교습.학원   1  1.154561e+09  2025
2      176211                노래방/노래방   1  1.154561e+09  2025
3      176212        미용실두발전문/미용실두발전문   1  1.154561e+09  2025
4      176213            일반음식점/일반음식점   1  1.154561e+09  2025

## local_money 행정동 중복값 확인

In [12]:
# 같은 월·행정동에 매출 행이 여러 개 있는지 확인
duplicate_mask = local_sales.duplicated(
    subset=["기준년월", "행정동코드"],
    keep=False
)

print("중복에 해당하는 행 수:", duplicate_mask.sum())
display(local_sales.loc[duplicate_mask])

중복에 해당하는 행 수: 0

Empty DataFrame
Columns: [기준년월, 행정동코드, 매출금액, 활성화비율]
Index: []

## local_live 컬럼명 동일하게 변경 (기준연월 -> 기준년월)

In [13]:
local_live = local_live.rename(
    columns={"기준연월": "기준년월"}
)

In [14]:
# 1. 모든 데이터의 행정동코드를 문자열로 통일
for data in [local_sales, local_live, local_move, local_store]:
    data["행정동코드"] = (
        data["행정동코드"]
        .astype("Int64")
        .astype("string")
        .str.zfill(10)
    )

# 2. 월별 자료의 기준년월을 정수형으로 통일
for data in [local_sales, local_live, local_move]:
    data["기준년월"] = data["기준년월"].astype("Int64")

# 3. 분석 기간으로 제한
local_sales = local_sales.loc[
    local_sales["기준년월"].between(202307, 202506)
].copy()

local_live = local_live.loc[
    local_live["기준년월"].between(202307, 202506)
].copy()

local_move = local_move.loc[
    local_move["기준년월"].between(202307, 202506)
].copy()

# 4. 점포 자료는 2023~2025년 자료 유지
local_store["년도"] = local_store["년도"].astype("Int64")

local_store = local_store.loc[
    local_store["년도"].between(2023, 2025)
].copy()

In [15]:
for name, data in [
    ("slaes", local_sales),
    ("live", local_live),
    ("move", local_move)
]:
    print(
        f"{name}: "
        f"전체 월 수 {data['기준년월'].nunique()}개 / "
        f"행정동 수 {data['행정동코드'].nunique()}개 / "
        f"월·행정동 중복 {data.duplicated(['기준년월', '행정동코드']).sum()}건 / "
        f"병합키 결측 {data[['기준년월', '행정동코드']].isna().any(axis=1).sum()}건"
    )

print("\n점포 자료의 연도별 행정동 수")
display(local_store.groupby("년도")["행정동코드"].nunique())

slaes: 전체 월 수 24개 / 행정동 수 463개 / 월·행정동 중복 0건 / 병합키 결측 0건
live: 전체 월 수 24개 / 행정동 수 464개 / 월·행정동 중복 0건 / 병합키 결측 0건
move: 전체 월 수 24개 / 행정동 수 607개 / 월·행정동 중복 0건 / 병합키 결측 0건

점포 자료의 연도별 행정동 수

년도
2023    576
2024    606
2025    606
Name: 행정동코드, dtype: int64

## 무결한 행정동 찾기

In [16]:
# 1. 월별 자료에서 24개월 모두 존재하는 행정동 찾기
complete_dongs = {}

for name, data in [
    ("sales", local_sales),
    ("live", local_live),
    ("move", local_move)
]:
    month_count = data.groupby("행정동코드")["기준년월"].nunique()

    complete_dongs[name] = set(
        month_count[month_count == 24].index
    )

    print(f"{name}: 24개월 모두 존재하는 행정동 {len(complete_dongs[name])}개")


# 2. 점포 자료에서 2023·2024·2025년 모두 존재하는 행정동 찾기
year_count = local_store.groupby("행정동코드")["년도"].nunique()

complete_dongs["store"] = set(
    year_count[year_count == 3].index
)

print(f"store: 3개년 모두 존재하는 행정동 {len(complete_dongs['store'])}개")


# 3. 네 데이터의 공통 행정동
common_dongs = (
    complete_dongs["sales"]
    & complete_dongs["live"]
    & complete_dongs["move"]
    & complete_dongs["store"]
)

print(f"\n최종 공통 행정동: {len(common_dongs)}개")
print(f"예상 병합 후 행 수: {len(common_dongs) * 24:,}행")

sales: 24개월 모두 존재하는 행정동 400개
live: 24개월 모두 존재하는 행정동 464개
move: 24개월 모두 존재하는 행정동 544개
store: 3개년 모두 존재하는 행정동 557개

최종 공통 행정동: 260개
예상 병합 후 행 수: 6,240행

## 행정동 결측이 많은 데이터셋 확인

In [17]:
dong_check = pd.DataFrame({
    "행정동코드": sorted(complete_dongs["sales"])
})

dong_check["인구_24개월"] = dong_check["행정동코드"].isin(
    complete_dongs["live"]
)

dong_check["유동인구_24개월"] = dong_check["행정동코드"].isin(
    complete_dongs["move"]
)

dong_check["점포_3개년"] = dong_check["행정동코드"].isin(
    complete_dongs["store"]
)

# 조건 조합별 행정동 수
check_summary = (
    dong_check
    .groupby(["인구_24개월", "유동인구_24개월", "점포_3개년"])
    .size()
    .reset_index(name="행정동수")
)

display(check_summary)

   인구_24개월  유동인구_24개월  점포_3개년  행정동수
0    False      False   False    26
1    False      False    True     4
2    False       True    True   109
3     True       True   False     1
4     True       True    True   260

- 지역화폐 매출, 생활인구, 유동인구, 업종 별 매장 수 모든 데이터셋을 활용하기 위해 260개의 행정동만 사용하기로 결정

## 데이터 셋 병합

In [18]:
# 1. 공통 행정동 260개만 선택
sales = local_sales.loc[
    local_sales["행정동코드"].isin(common_dongs)
].copy()

live = local_live.loc[
    local_live["행정동코드"].isin(common_dongs)
].copy()

move = local_move.loc[
    local_move["행정동코드"].isin(common_dongs)
].copy()

store = local_store.loc[
    local_store["행정동코드"].isin(common_dongs)
].copy()


# 2. 점포 자료: 연도·행정동별 업종 개수를 가로로 펼치기
store_wide = store.pivot_table(
    index=["년도", "행정동코드"],
    columns="업종명(종목명)",
    values="개수",
    aggfunc="sum",
    fill_value=0
).add_prefix("점포수_").reset_index()

store_wide.columns.name = None


# 3. 매출 + 인구 자료
merged_df = sales.merge(
    live[["기준년월", "행정동코드", "행정구역", "총인구수"]],
    on=["기준년월", "행정동코드"],
    how="left",
    validate="one_to_one"
)


# 4. 유동인구 자료 추가
merged_df = merged_df.merge(
    move[["기준년월", "행정동코드", "월유동인구수"]],
    on=["기준년월", "행정동코드"],
    how="left",
    validate="one_to_one"
)


# 5. 연도 생성 후 점포 자료 추가
merged_df["년도"] = merged_df["기준년월"] // 100

merged_df = merged_df.merge(
    store_wide,
    on=["년도", "행정동코드"],
    how="left",
    validate="many_to_one"
)


# 6. 행정동·월 순서로 정렬
merged_df = merged_df.sort_values(
    ["행정동코드", "기준년월"]
).reset_index(drop=True)

# 7. 병합 결과 확인
print("행·열 수:", merged_df.shape)
print("행정동 수:", merged_df["행정동코드"].nunique())
print(
    "월·행정동 중복:",
    merged_df.duplicated(["기준년월", "행정동코드"]).sum()
)

display(merged_df.head())

# 결측치가 있는 컬럼만 표시
missing = merged_df.isna().sum()
display(missing[missing > 0])

행·열 수: (6240, 890)
행정동 수: 260
월·행정동 중복: 0

,기준년월,행정동코드,매출금액,활성화비율,행정구역,총인구수,월유동인구수,년도,점포수_/아이스크림전문점,점포수_SK주유소,...,점포수_화장품,점포수_화장품 / 화장품,점포수_화장품/화장품,점포수_회원제형태 / 건강식품,점포수_회원제형태 / 기타1,점포수_회원제형태 / 기타3,점포수_회원제형태 / 기타4,점포수_회원제형태 / 레져업소,점포수_회원제형태 / 서적,점포수_회원제형태 / 학원
0,202307,4111156000,41128684.0,100.0,경기도 수원시 장안구 파장동,22480.0,241011.94,2023,0,0,...,7,0,0,0,0,0,0,0,0,0
1,202308,4111156000,5115679.0,100.0,경기도 수원시 장안구 파장동,22451.0,241268.02,2023,0,0,...,7,0,0,0,0,0,0,0,0,0
2,202309,4111156000,436318.0,100.0,경기도 수원시 장안구 파장동,22410.0,236580.40,2023,0,0,...,7,0,0,0,0,0,0,0,0,0
3,202310,4111156000,631469.0,100.0,경기도 수원시 장안구 파장동,23628.0,268762.16,2023,0,0,...,7,0,0,0,0,0,0,0,0,0
4,202311,4111156000,591386.0,100.0,경기도 수원시 장안구 파장동,24542.0,253510.66,2023,0,0,...,7,0,0,0,0,0,0,0,0,0

Series([], dtype: int64)

## 중복열 정리

In [19]:
print("점포 자료 컬럼:")
print(local_store.columns.tolist())

print("\n병합에 사용된 업종 종류 수:")
print(store["업종명(종목명)"].nunique())

print("\n전체 업종 목록:")
industry_list = (
    store["업종명(종목명)"]
    .dropna()
    .drop_duplicates()
    .sort_values()
)

print(industry_list.to_string(index=False))

점포 자료 컬럼:
['Unnamed: 0', '업종명(종목명)', '개수', '행정동코드', '년도']

병합에 사용된 업종 종류 수:
882

전체 업종 목록:
                /아이스크림전문점
                    SK주유소
                가구 / 기타가구
                가구 / 일반가구
                가구 / 철제가구
                    가구판매점
            가구판매점 / 가구판매점
              가구판매점/가구판매점
                       가발
                  가발 / 가발
                    가발/가발
                       가방
                   가방.핸드백
          가방.핸드백 / 가방.핸드백
            가방.핸드백/가방.핸드백
                    가전/통신
                     가전제품
                가전제품/가전제품
                   각종단체회비
            각종단체회비/각종단체회비
                   건강보조식품
          건강보조식품 / 건강보조식품
            건강보조식품/건강보조식품
            건강식품 / 기타건강식품
              건강식품 / 홍삼제품
                 건위생 / 안경
              건위생 / 피부미용실
                  건축용요업제품
          건축자재 / 건축용 요업제품
            건축자재 / 기타건축자재
          건축자재 / 목재 석재 철물
          건축자재 / 목재?석재?철물
          건축자재 / 목재·석재·철물
         건축자재 / 보일러 펌프 샷시
         건축자재 / 보일러?펌프?샷시
         건축자재 / 보일러·펌프·샷시
                건축자재 / 유리
            건축자재 / 인테리어전문
              건축자재 / 조명기구
               건축자재 / 페인트
                    골프연습장
            골프연습장 / 골프연습장
              골프연습장/골프연습장
                  골프용품전문점
                      골프장
                  골프장/골프장
                  공공편의서비스
          공공편의서비스/공공편의서비스
                      공과금
                     관광여행
                 광고기획.대행업
      광고기획.대행업 / 광고기획.대행업
        광고기획.대행업/광고기획.대행업
               광학제품 / 사진관
               광학제품 / 카메라
                       교복
                  교복 / 교복
                    교복/교복
                    교육및교구
            교육및교구 / 교육및교구
              교육및교구/교육및교구
                   교육서비스업
                    구두.신발
            구두.신발 / 구두.신발
              구두.신발/구두.신발
                     국산신차
                     귀금속점
                    기계.장비
                기계.장비(기타)
                  기계.장비기타
            기계.장비기타/기계.장비
          기계.장비기타/기계.장비기타
                     기계공구
                     기념품점
                     기능학원
                      기부금
                  기부금/기부금
                기술.직업훈력학원
    기술.직업훈력학원 / 기술.직업훈력학원
      기술.직업훈력학원/기술.직업훈력학원
                기술.직업훈련학원
                       기타
                기타 / 기계공구
                  기타 / 기타
              기타 / 기타 전문점
                  기타 운송수단
                    기타/기타
                     기타가구
                  기타가례서비스
        기타가례서비스 / 기타가례서비스
          기타가례서비스/기타가례서비스
                기타가정.주방용품
    기타가정.주방용품 / 기타가정.주방용품
      기타가정.주방용품/기타가정.주방용품
                   기타건강식품
                   기타건축자재
          기타건축자재 / 기타건축자재
            기타건축자재/기타건축자재
               기타교육.교습.학원
  기타교육.교습.학원 / 기타교육.교습.학원
    기타교육.교습.학원/기타교육.교습.학원
                  기타대인서비스
        기타대인서비스 / 기타대인서비스
          기타대인서비스/기타대인서비스
               기타레저,스포츠용품
  기타레저,스포츠용품 / 기타레저,스포츠용품
    기타레저,스포츠용품/기타레저,스포츠용품
                   기타레져업소
                    기타무점포
              기타무점포/기타무점포
                 기타부동산관련업
      기타부동산관련업 / 기타부동산관련업
        기타부동산관련업/기타부동산관련업
                  기타사무용기기
          기타사무용기기/기타사무용기기
                   기타사무용품
               기타상설할인.아울렛
    기타상설할인.아울렛/기타상설할인.아울렛
                  기타상품판매점
        기타상품판매점 / 기타상품판매점
          기타상품판매점/기타상품판매점
                    기타서비스
            기타서비스 / 기타서비스
              기타서비스/기타서비스
                   기타서적문구
                기타수리.수선전문
    기타수리.수선전문 / 기타수리.수선전문
      기타수리.수선전문/기타수리.수선전문
                    기타숙박업
                   기타숙박업소
          기타숙박업소 / 기타숙박업소
            기타숙박업소/기타숙박업소
                  기타승객운송업
          기타승객운송업/기타승객운송업
                   기타식음료품
          기타식음료품 / 기타식음료품
            기타식음료품/기타식음료품
                기타약품.의료기기
    기타약품.의료기기 / 기타약품.의료기기
      기타약품.의료기기/기타약품.의료기기
                   기타연료판매
            기타연료판매/기타연료판매
                기타오락.휴식시설
    기타오락.휴식시설 / 기타오락.휴식시설
      기타오락.휴식시설/기타오락.휴식시설
                     기타요금
                기타요금/기타요금
                  기타용역서비스
                   기타운송기구
            기타운송기구/기타운송기구
                    기타음식점
            기타음식점 / 기타음식점
              기타음식점/기타음식점
 기타의료기관 / 기타의료기관 및 기타의료기기
            기타의료기관 / 동물병원
           기타의료기관 / 산후조리원
            기타의료기관및기타의료기기
                    기타의료업
              기타의료업/기타의료업
                     기타의류
                     기타잡화
              기타잡화 / 기타잡화
                기타잡화/기타잡화
                   기타장비임대
          기타장비임대 / 기타장비임대
            기타장비임대/기타장비임대
                  기타전문서비스
          기타전문서비스/기타전문서비스
                    기타전문점
                   기타전자제품
            기타전자제품/기타전자제품
                  기타종합소매점
        기타종합소매점 / 기타종합소매점
          기타종합소매점/기타종합소매점
                     기타주점
                기타주점/기타주점
              기타취미.레저.스포츠
기타취미.레저.스포츠 / 기타취미.레저.스포츠
  기타취미.레저.스포츠/기타취미.레저.스포츠
                       내과
                  내과 / 내과
                    내과/내과
                      내의류
                  내의류/내의류
                     냉열기기
                      노래방
                노래방 / 노래방
                  노래방/노래방
                  농산물,청과물
        농산물,청과물 / 농산물,청과물
          농산물,청과물/농산물,청과물
                   농수축산물점
                  농수축협직판장
          농수축협직판장/농수축협직판장
              농업 / 기타농업관련
                 농업 / 농기계
            농업 / 비료,사료,종자
                  농협식품전문점
          농협식품전문점/농협식품전문점
                     단란주점
                      단체복
                      당구장
                당구장 / 당구장
                  당구장/당구장
                     대리운전
                대리운전/대리운전
                    대형할인점
              대형할인점/대형할인점
              도서/문화/공연/오락
                      독서실
                     동물병원
              동물병원 / 동물병원
                동물병원/동물병원
          동차정비 유지 / 자동차정비
       레저/문화 용품 / 골프용품전문점
           레저/문화 용품 / 악기점
      레저/스포츠 서비스 / 기타레져업소
         레저/스포츠 서비스 / 노래방
         레저/스포츠 서비스 / 당구장
         레저/스포츠 서비스 / 수영장
       레저/스포츠 서비스 / 스크린골프
        레저/스포츠 서비스 / 테니스장
        레저/스포츠 서비스 / 헬스클럽
             레저업소 / 골프연습장
            레저업소 / 기타레져업소
             레저업소 / 노 래 방
             레저업소 / 당 구 장
             레저업소 / 볼 링 장
             레저업소 / 수 영 장
             레저업소 / 스크린골프
              레저업소 / 테니스장
              레저업소 / 헬스클럽
                 레저용 숙박업소
        레저용 숙박업소/레저용 숙박업소
                  레저용숙박업소
                     레져업소
          레져용품 / 골프용품 전문점
          레져용품 / 스포츠 레져용품
          레져용품 / 스포츠?레져용품
               레져용품 / 악기점
            레져용품 / 음반/영상물
            레져용품 / 피아노대리점
                   레져용품수리
                    레포츠클럽
            료식품 / 농 축 수산품
                   류 / 정장
               리서비스 / 세탁소
                     맞춤복점
                      면세점
                   모피.무스탕
            모피.무스탕/모피.무스탕
                 목재·석재·철물
                   무수도장 등
               무수도장 등(학원)
                 무수도장 등학원
      무수도장 등학원 / 무수도장 등학원
          무수도장 등학원/무수도장 등
        무수도장 등학원/무수도장 등학원
               무술도장 등(학원)
                  문구,사무용품
        문구,사무용품 / 문구,사무용품
          문구,사무용품/문구,사무용품
                     문구용품
                    문리계학원
           문화.취미 / 문화취미기타
           문화.취미 / 민예 공예품
           문화.취미 / 민예?공예품
              문화.취미 / 수족관
             문화.취미 / 애완동물
               문화.취미 / 화랑
           문화.취미 / 화방 표구점
           문화.취미 / 화방?표구점
               문화.취미 / 화원
           문화/취미 / 문화취미기타
              문화/취미 / 사진관
             문화/취미 / 애완동물
               문화/취미 / 화원
                   문화취미기타
                      미곡상
                    미용 기타
                 미용/뷰티/위생
              미용/위생 / 미용원
             미용/위생 / 미용재료
               미용/위생 / 안경
        미용/위생 / 안마/스포츠마사지
              미용/위생 / 이용원
            미용/위생 / 피부미용실
                      미용실
                미용실(두발전문)
                  미용실두발전문
        미용실두발전문 / 미용실두발전문
          미용실두발전문/미용실두발전문
                      미용원
                     미용재료
              미용재료 / 미용재료
                미용재료/미용재료
                민예 공예 토산품
                   민예·공예품
                  민예품.공예품
        민예품.공예품 / 민예품.공예품
          민예품.공예품/민예품.공예품
             반휴게음식 / 서양음식
             반휴게음식 / 일반한식
                  법무전문서비스
          법무전문서비스/법무전문서비스
               변잡화 / 기타잡화
                       병원
                  병원 / 병원
                병원 / 종합병원
                병원 / 치과병원
                병원 / 한방병원
           보건위생 / 기타대인서비스
               보건위생 / 미용원
              보건위생 / 미용재료
               보건위생 / 사우나
                보건위생 / 안경
             보건위생 / 안마시술소
              보건위생 / 의료용품
               보건위생 / 이용원
             보건위생 / 피부미용실
               보건위생 / 화장품
                     보습학원
                보일러,펌프,샷시
    보일러,펌프,샷시 / 보일러,펌프,샷시
      보일러,펌프,샷시/보일러,펌프,샷시
                보일러·펌프·샷시
                      볼링장
                    부동산중개
              부동산중개/부동산중개
                       뷔페
                  뷔페.출장연회
                  뷔페/출장연회
        뷔페/출장연회 / 뷔페/출장연회
          뷔페/출장연회/뷔페/출장연회
                   비디오.음반
            비디오.음반/비디오.음반
                 비료.사료.종자
        비료.사료.종자/비료.사료.종자
                 비료·사료·종자
                  비영리/비대상
                    사무서비스
           사무통신 / 기타 사무용품
          사무통신 / 사무용 OA기기
               사무통신 / 컴퓨터
              사무통신 / 통신기기
                      사우나
              사우나.목욕탕.찜질방
사우나.목욕탕.찜질방 / 사우나.목욕탕.찜질방
  사우나.목욕탕.찜질방/사우나.목욕탕.찜질방
                      사진관
                  사진관.현상소
        사진관.현상소 / 사진관.현상소
          사진관.현상소/사진관.현상소
                     산부인과
                산부인과/산부인과
                    산후조리원
              산후조리원/산후조리원
                   서양식전문점
          서양식전문점 / 서양식전문점
            서양식전문점/서양식전문점
                       서적
                   서적(출판)
        서적/문구/학습자재 / 문구용품
             서적문구 / 과학기자재
            서적문구 / 기타서적문구
              서적문구 / 문구용품
               서적문구 / 완구점
              서적문구 / 일반서적
              서적문구 / 전문서적
          서적문구 / 출판 및 인쇄물
                     서적출판
              서적출판 / 서적출판
                  서적출판/서적
                서적출판/서적출판
                    선물용품점
              선물용품점/선물용품점
                     성형외과
                성형외과/성형외과
                  세무전문서비스
          세무전문서비스/세무전문서비스
                      세차장
                세차장 / 세차장
                  세차장/세차장
                      세탁소
                      세탁업
                세탁업 / 세탁업
                  세탁업/세탁업
                      소매업
                     소비조합
               소비조합(구내매점)
                 소비조합구내매점
        소비조합구내매점/소비조합구내매점
                      소아과
                  소아과/소아과
                    소프트웨어
           수리서비스 / 가정용품수리
          수리서비스 / 기타수리서비스
           수리서비스 / 레져용품수리
        수리서비스 / 사무 통신기기수리
        수리서비스 / 사무?통신기기수리
              수리서비스 / 세탁소
           수리서비스 / 신변잡화수리
                  수산물,건어물
        수산물,건어물 / 수산물,건어물
          수산물,건어물/수산물,건어물
                      수족관
                  수집품,기념품
          수집품,기념품/수집품,기념품
                      숙박업
           숙박업 / 여관/기타숙박업
                     슈퍼마켓
                  슈퍼마켓.마트
        슈퍼마켓.마트 / 슈퍼마켓.마트
          슈퍼마켓.마트/슈퍼마켓.마트
                       스넥
                 스포츠·레져용품
                   스포츠용품점
            스포츠용품점/스포츠용품점
                    스포츠의류
                       시계
                   시계.귀금속
            시계.귀금속/시계.귀금속
                      식음료
                  식음료(기타)
                    식음료기타
            식음료기타 / 식음료기타
                식음료기타/식음료
              식음료기타/식음료기타
                    신경정신과
              신경정신과/신경정신과
                       신발
                신변잡화 / 가방
               신변잡화 / 귀금속
              신변잡화 / 기념품점
              신변잡화 / 기타잡화
                신변잡화 / 시계
                신변잡화 / 신발
              신변잡화 / 액세서리
                신변잡화 / 제화
                     실내장식
               실내장식(인테리어)
                 실내장식인테리어
            실내장식인테리어/실내장식
        실내장식인테리어/실내장식인테리어
                   아동.유아복
          아동.유아복 / 아동.유아복
            아동.유아복/아동.유아복
                   아동·유아복
                 아이스크림전문점
      아이스크림전문점 / 아이스크림전문점
        아이스크림전문점/아이스크림전문점
                    악기판매점
              악기판매점/악기판매점
                       안경
                  안경.광학제품
        안경.광학제품 / 안경.광학제품
          안경.광학제품/안경.광학제품
                       안과
                  안과 / 안과
                    안과/안과
                    안마시술소
              안마시술소/안마시술소
                     애완동물
                  애완동물,용품
             애완동물,용품(수족관)
               애완동물,용품수족관
  애완동물,용품수족관 / 애완동물,용품수족관
       애완동물,용품수족관/애완동물,용품
    애완동물,용품수족관/애완동물,용품수족관
                     액세서리
                       약국
                  약국 / 약국
                 약국 / 한약방
                    약국/약국
                  양복점.한복점
        양복점.한복점 / 양복점.한복점
          양복점.한복점/양복점.한복점
                여행 / 고속버스
                여행 / 관광여행
                 여행 / 렌터카
                  여행 / 택시
                      여행사
                  여행사/여행사
                  여행지원서비스
          여행지원서비스/여행지원서비스
            역 서비스 / 사무서비스
          연료판매점 / E1가스충전소
            연료판매점 / GS주유소
          연료판매점 / LPG 취급점
            연료판매점 / SK주유소
             연료판매점 / 기타연료
          연료판매점 / 쌍용S-OIL
             연료판매점 / 유류판매
              연료판매점 / 주유소
             연료판매점 / 현대정유
                   영화.공연장
            영화.공연장/영화.공연장
                  예·체능계학원
                  예술품.골동품
          예술품.골동품/예술품.골동품
                      예식장
                  예식장/예식장
                  예체능계열학원
        예체능계열학원 / 예체능계열학원
          예체능계열학원/예체능계열학원
                      오락실
                  오락실/PC방
          오락실/PC방/오락실/PC방
               오양.보육.복지시설
    오양.보육.복지시설/오양.보육.복지시설
                     오토바이
              오토바이 / 오토바이
                오토바이/오토바이
                     오픈마켓
                       완구
                  완구 / 완구
                    완구/완구
                       외과
                    외과/외과
                    외국어학원
            외국어학원 / 외국어학원
              외국어학원/외국어학원
                       요가
               요양.보육.복지시설
                     요양병원
                요양병원/요양병원
         용실두발전문 / 미용실두발전문
         용역 서비스 / 기타용역서비스
         용역 서비스 / 법률회계서비스
       용역 서비스 / 법률회계서비스개인
         용역 서비스 / 보관및 창고업
       용역 서비스 / 부동산 중개?임대
           용역 서비스 / 사무서비스
           용역 서비스 / 소프트웨어
            용역 서비스 / 종합용역
           용역 서비스 / 혼례서비스
            용역 서비스 / 화물운송
          용역서비스 / 기타대인서비스
            용역서비스 / 사무서비스
              용역서비스 / 세탁소
            용역서비스 / 소프트웨어
             용역서비스 / 종합용역
                      운송업
              원 / 기타 교육기관
                  원 / 독서실
                 원 / 보습학원
             원 / 예 체능계학원
                원 / 외국어학원
                  웨딩토탈서비스
          웨딩토탈서비스/웨딩토탈서비스
                    위탁급식업
                      유아원
                      유치원
                  유치원/유치원
           유통업 비영리 / 구내매점
      유통업 비영리 / 농,축협 직영매장
           유통업 영리 / 기타유통업
            유통업 영리 / 슈퍼마켓
           유통업 영리 / 편 의 점
                  유흥.사치용품
          유흥.사치용품/유흥.사치용품
                     유흥주점
                유흥주점/유흥주점
                  윤활유전문판매
           음료/식품 / 기타건강식품
           음료/식품 / 기타음료식품
          음료/식품 / 농·축·수산품
              음료/식품 / 정육점
            음료식품 / 기타음료식품
           음료식품 / 농 축 수산품
           음료식품 / 농?축?수산품
               음료식품 / 미곡상
               음료식품 / 정육점
               음료식품 / 제과점
            음료식품 / 주류 판매점
                     의료용품
                의류 / 기타의류
                의류 / 내의판매
                 의류 / 단체복
                의류 / 맞춤복점
               의류 / 스포츠의류
                의류 / 아동의류
                  의류 / 정장
                 의류/잡화/안경
                    의류/정장
                     의류관련
                 의류관련(기타)
                   의류관련기타
            의류관련기타/의류관련기타
                    의약품판매
              의약품판매/의약품판매
                       의원
                  의원 / 의원
                의원 / 치과의원
                 의원 / 한의원
                      이발소
                이발소 / 이발소
                  이발소/이발소
                    이비인후과
            이비인후과 / 이비인후과
              이비인후과/이비인후과
                       이사
                 이사/화물운송업
        이사/화물운송업/이사/화물운송업
                      이용원
                    인삼전문점
              인삼전문점/인삼전문점
                   인터넷상거래
          인터넷상거래 / 인터넷상거래
            인터넷상거래/인터넷상거래
                   인테리어전문
                일반 치과 한의원
          일반/휴게 음식 / 서양음식
            일반/휴게 음식 / 스넥
          일반/휴게 음식 / 일반한식
         일반/휴게 음식 / 일식·회집
           일반/휴게 음식 / 제과점
            일반/휴게 음식 / 주점
           일반/휴게 음식 / 중국식
                     일반가구
                     일반병원
                일반병원/일반병원
                    일반상품권
              일반상품권/일반상품권
                     일반서적
              일반유통 / 슈퍼마켓
               일반유통 / 편의점
                    일반음식점
            일반음식점 / 일반음식점
              일반음식점/일반음식점
                     일반의류
              일반의류 / 일반의류
                일반의류/일반의류
                     일반주점
              일반주점 / 일반주점
                일반주점/일반주점
                     일반한식
            일반휴게음식 / 서양음식
              일반휴게음식 / 스넥
           일반휴게음식 / 위탁급식업
            일반휴게음식 / 일반한식
           일반휴게음식 / 일식 회집
           일반휴게음식 / 일식?회집
              일반휴게음식 / 주점
             일반휴게음식 / 중국식
            일반휴게음식 / 칵테일바
                    일식·회집
                    일식전문점
            일식전문점 / 일식전문점
              일식전문점/일식전문점
                입시학원,보습학원
    입시학원,보습학원 / 입시학원,보습학원
      입시학원,보습학원/입시학원,보습학원
                      자동차
        자동차 정비/유지 / 자동차부품
                자동차(국산신차)
                자동차(수입신차)
                 자동차(중고차)
                  자동차/자전거
                  자동차국산신차
          자동차국산신차/자동차국산신차
                    자동차부품
          자동차수입신차/자동차수입신차
                자동차시트·타이어
                  자동차운전학원
          자동차운전학원/자동차운전학원
                    자동차정비
            자동차정비 / 자동차정비
      자동차정비 유지 / 가타자동차서비스
           자동차정비 유지 / 세차장
     자동차정비 유지 / 윤활유 전문 판매
         자동차정비 유지 / 자동차부품
     자동차정비 유지 / 자동차시트 타이어
     자동차정비 유지 / 자동차시트?타이어
         자동차정비 유지 / 자동차정비
           자동차정비 유지 / 주차장
         자동차정비 유지 / 카인테리어
              자동차정비/자동차정비
            자동차중고차/자동차중고차
            자동차판매 / 이륜차판매
          자동차판매 / 중고자동차판매
                      자전거
                자전거 / 자전거
                  자전거/자전거
               저업소 / 헬스클럽
              전기제품 / 가전제품
            전기제품 / 기타전기제품
              전기제품 / 냉열기기
                 전문스포츠용품점
      전문스포츠용품점 / 전문스포츠용품점
        전문스포츠용품점/전문스포츠용품점
                      점술업
                점술업 / 점술업
                  점술업/점술업
                    정기간행물
                   정수기.비데
            정수기.비데/정수기.비데
                       정장
                     정형외과
              정형외과 / 정형외과
                정형외과/정형외과
                    제과.제빵
            제과.제빵 / 제과.제빵
              제과.제빵/제과.제빵
                      제과점
             제약회사/의약품도매업체
                      제조업
                       제화
                     조명기구
                  조명기구.전기
          조명기구.전기/조명기구.전기
                   종합레저타운
            종합레저타운/종합레저타운
                     종합병원
                     종합용역
                    주류전문점
            주류전문점 / 주류전문점
              주류전문점/주류전문점
                    주류판매점
               주방용구 / 정수기
              주방용구 / 주방용구
             주방용구 / 주방용식기
                      주유소
                주유소 / 주유소
                 주유소(LPG)
                  주유소/주유소
                   주유소LPG
            주유소LPG/주유소LPG
                       주점
                      주차장
                  주차장.폐차장
          주차장.폐차장/주차장.폐차장
                   중고품판매점
          중고품판매점 / 중고품판매점
            중고품판매점/중고품판매점
                      중국식
                    중식전문점
            중식전문점 / 중식전문점
              중식전문점/중식전문점
                직물 / 기타직물
               직물 / 옷감 직물
               직물 / 옷감?직물
              직물 / 침구 수예점
              직물 / 침구?수예점
        직물 / 카페트,커튼,천막,지물
               직물 / 혼수전문점
          직물/침구류 / 침구·수예점
            차량 정비/부품/인테리어
                  차량견인서비스
          차량견인서비스/차량견인서비스
                  차량부품.용품
        차량부품.용품 / 차량부품.용품
          차량부품.용품/차량부품.용품
                    차량임대
               차량임대 (렌터카)
           차량임대 렌터카/차량임대
        차량임대 렌터카/차량임대 렌터카
                차량임대(렌터카)
                  차량임대렌터가
                    창고보관업
            창고보관업 / 창고보관업
              창고보관업/창고보관업
                 철재,사무용가구
        철재,사무용가구/철재,사무용가구
                    체인스토어

In [20]:
# 원본 업종명은 유지하고 정리용 컬럼 생성
def clean_industry(value):
    if pd.isna(value):
        return pd.NA

    # 공백 제거
    name = "".join(str(value).split())

    # 슬래시 앞뒤가 완전히 같은 경우에만 하나로 줄이기
    for i, char in enumerate(name):
        if char == "/" and name[:i] == name[i + 1:]:
            return name[:i]

    return name


store["업종명_정리"] = store["업종명(종목명)"].apply(clean_industry)

print("정리 전:", store["업종명(종목명)"].nunique())
print("정리 후:", store["업종명_정리"].nunique())

정리 전: 882
정리 후: 593

In [21]:
industry_list = (
    store["업종명_정리"]
    .dropna()
    .drop_duplicates()
    .sort_values()
)

print(industry_list.to_string(index=False))

           /아이스크림전문점
               SK주유소
             가구/기타가구
             가구/일반가구
             가구/철제가구
               가구판매점
                  가발
                  가방
              가방.핸드백
               가전/통신
                가전제품
              각종단체회비
              건강보조식품
         건강식품/기타건강식품
           건강식품/홍삼제품
              건위생/안경
           건위생/피부미용실
             건축용요업제품
        건축자재/건축용요업제품
         건축자재/기타건축자재
       건축자재/목재?석재?철물
       건축자재/목재·석재·철물
         건축자재/목재석재철물
      건축자재/보일러?펌프?샷시
      건축자재/보일러·펌프·샷시
        건축자재/보일러펌프샷시
             건축자재/유리
         건축자재/인테리어전문
           건축자재/조명기구
            건축자재/페인트
               골프연습장
             골프용품전문점
                 골프장
             공공편의서비스
                 공과금
                관광여행
            광고기획.대행업
            광학제품/사진관
            광학제품/카메라
                  교복
               교육및교구
              교육서비스업
               구두.신발
                국산신차
                귀금속점
               기계.장비
           기계.장비(기타)
             기계.장비기타
       기계.장비기타/기계.장비
                기계공구
                기념품점
                기능학원
                 기부금
           기술.직업훈력학원
           기술.직업훈련학원
                  기타
             기타/기계공구
            기타/기타전문점
                기타가구
             기타가례서비스
           기타가정.주방용품
              기타건강식품
              기타건축자재
          기타교육.교습.학원
             기타대인서비스
          기타레저,스포츠용품
              기타레져업소
               기타무점포
            기타부동산관련업
             기타사무용기기
              기타사무용품
          기타상설할인.아울렛
             기타상품판매점
               기타서비스
              기타서적문구
           기타수리.수선전문
               기타숙박업
              기타숙박업소
             기타승객운송업
              기타식음료품
           기타약품.의료기기
              기타연료판매
           기타오락.휴식시설
                기타요금
             기타용역서비스
              기타운송기구
              기타운송수단
               기타음식점
기타의료기관/기타의료기관및기타의료기기
         기타의료기관/동물병원
        기타의료기관/산후조리원
       기타의료기관및기타의료기기
               기타의료업
                기타의류
                기타잡화
              기타장비임대
             기타전문서비스
               기타전문점
              기타전자제품
             기타종합소매점
                기타주점
         기타취미.레저.스포츠
                  내과
                 내의류
                냉열기기
                 노래방
             농산물,청과물
              농수축산물점
             농수축협직판장
           농업/기타농업관련
              농업/농기계
         농업/비료,사료,종자
             농협식품전문점
                단란주점
                 단체복
                 당구장
                대리운전
               대형할인점
         도서/문화/공연/오락
                 독서실
                동물병원
        동차정비유지/자동차정비
     레저/문화용품/골프용품전문점
         레저/문화용품/악기점
    레저/스포츠서비스/기타레져업소
       레저/스포츠서비스/노래방
       레저/스포츠서비스/당구장
       레저/스포츠서비스/수영장
     레저/스포츠서비스/스크린골프
      레저/스포츠서비스/테니스장
      레저/스포츠서비스/헬스클럽
          레저업소/골프연습장
         레저업소/기타레져업소
            레저업소/노래방
            레저업소/당구장
            레저업소/볼링장
            레저업소/수영장
          레저업소/스크린골프
           레저업소/테니스장
           레저업소/헬스클럽
             레저용숙박업소
                레져업소
        레져용품/골프용품전문점
       레져용품/스포츠?레져용품
        레져용품/스포츠레져용품
            레져용품/악기점
         레져용품/음반/영상물
         레져용품/피아노대리점
              레져용품수리
               레포츠클럽
           료식품/농축수산품
                류/정장
            리서비스/세탁소
                맞춤복점
                 면세점
              모피.무스탕
            목재·석재·철물
               무수도장등
           무수도장등(학원)
             무수도장등학원
       무수도장등학원/무수도장등
           무술도장등(학원)
             문구,사무용품
                문구용품
               문리계학원
        문화.취미/문화취미기타
        문화.취미/민예?공예품
         문화.취미/민예공예품
           문화.취미/수족관
          문화.취미/애완동물
            문화.취미/화랑
        문화.취미/화방?표구점
         문화.취미/화방표구점
            문화.취미/화원
        문화/취미/문화취미기타
           문화/취미/사진관
          문화/취미/애완동물
            문화/취미/화원
              문화취미기타
                 미곡상
            미용/뷰티/위생
           미용/위생/미용원
          미용/위생/미용재료
            미용/위생/안경
     미용/위생/안마/스포츠마사지
           미용/위생/이용원
         미용/위생/피부미용실
                미용기타
                 미용실
           미용실(두발전문)
             미용실두발전문
                 미용원
                미용재료
              민예·공예품
             민예공예토산품
             민예품.공예품
          반휴게음식/서양음식
          반휴게음식/일반한식
             법무전문서비스
            변잡화/기타잡화
                  병원
             병원/종합병원
             병원/치과병원
             병원/한방병원
        보건위생/기타대인서비스
            보건위생/미용원
           보건위생/미용재료
            보건위생/사우나
             보건위생/안경
          보건위생/안마시술소
           보건위생/의료용품
            보건위생/이용원
          보건위생/피부미용실
            보건위생/화장품
                보습학원
           보일러,펌프,샷시
           보일러·펌프·샷시
                 볼링장
               부동산중개
                  뷔페
             뷔페.출장연회
             뷔페/출장연회
              비디오.음반
            비료.사료.종자
            비료·사료·종자
             비영리/비대상
               사무서비스
         사무통신/기타사무용품
        사무통신/사무용OA기기
            사무통신/컴퓨터
           사무통신/통신기기
                 사우나
         사우나.목욕탕.찜질방
                 사진관
             사진관.현상소
                산부인과
               산후조리원
              서양식전문점
                  서적
              서적(출판)
     서적/문구/학습자재/문구용품
          서적문구/과학기자재
         서적문구/기타서적문구
           서적문구/문구용품
            서적문구/완구점
           서적문구/일반서적
           서적문구/전문서적
         서적문구/출판및인쇄물
                서적출판
             서적출판/서적
               선물용품점
                성형외과
             세무전문서비스
                 세차장
                 세탁소
                 세탁업
                 소매업
                소비조합
          소비조합(구내매점)
            소비조합구내매점
                 소아과
               소프트웨어
        수리서비스/가정용품수리
       수리서비스/기타수리서비스
        수리서비스/레져용품수리
     수리서비스/사무?통신기기수리
      수리서비스/사무통신기기수리
           수리서비스/세탁소
        수리서비스/신변잡화수리
             수산물,건어물
                 수족관
             수집품,기념품
                 숙박업
        숙박업/여관/기타숙박업
                슈퍼마켓
             슈퍼마켓.마트
                  스넥
            스포츠·레져용품
              스포츠용품점
               스포츠의류
                  시계
              시계.귀금속
                 식음료
             식음료(기타)
               식음료기타
           식음료기타/식음료
               신경정신과
                  신발
             신변잡화/가방
            신변잡화/귀금속
           신변잡화/기념품점
           신변잡화/기타잡화
             신변잡화/시계
             신변잡화/신발
           신변잡화/액세서리
             신변잡화/제화
                실내장식
          실내장식(인테리어)
            실내장식인테리어
       실내장식인테리어/실내장식
              아동.유아복
              아동·유아복
            아이스크림전문점
               악기판매점
                  안경
             안경.광학제품
                  안과
               안마시술소
                애완동물
             애완동물,용품
        애완동물,용품(수족관)
          애완동물,용품수족관
  애완동물,용품수족관/애완동물,용품
                액세서리
                  약국
              약국/한약방
             양복점.한복점
             여행/고속버스
             여행/관광여행
              여행/렌터카
               여행/택시
                 여행사
             여행지원서비스
          역서비스/사무서비스
       연료판매점/E1가스충전소
         연료판매점/GS주유소
        연료판매점/LPG취급점
         연료판매점/SK주유소
          연료판매점/기타연료
       연료판매점/쌍용S-OIL
          연료판매점/유류판매
           연료판매점/주유소
          연료판매점/현대정유
              영화.공연장
             예·체능계학원
             예술품.골동품
                 예식장
             예체능계열학원
                 오락실
             오락실/PC방
          오양.보육.복지시설
                오토바이
                오픈마켓
                  완구
                  외과
               외국어학원
                  요가
          요양.보육.복지시설
                요양병원
      용실두발전문/미용실두발전문
       용역서비스/기타대인서비스
       용역서비스/기타용역서비스
       용역서비스/법률회계서비스
     용역서비스/법률회계서비스개인
        용역서비스/보관및창고업
      용역서비스/부동산중개?임대
         용역서비스/사무서비스
           용역서비스/세탁소
         용역서비스/소프트웨어
          용역서비스/종합용역
         용역서비스/혼례서비스
          용역서비스/화물운송
                 운송업
            원/기타교육기관
               원/독서실
              원/보습학원
            원/예체능계학원
             원/외국어학원
             웨딩토탈서비스
               위탁급식업
                 유아원
                 유치원
         유통업비영리/구내매점
     유통업비영리/농,축협직영매장
         유통업영리/기타유통업
          유통업영리/슈퍼마켓
           유통업영리/편의점
             유흥.사치용품
                유흥주점
             윤활유전문판매
        음료/식품/기타건강식품
        음료/식품/기타음료식품
       음료/식품/농·축·수산품
           음료/식품/정육점
         음료식품/기타음료식품
        음료식품/농?축?수산품
          음료식품/농축수산품
            음료식품/미곡상
            음료식품/정육점
            음료식품/제과점
          음료식품/주류판매점
                의료용품
             의류/기타의류
             의류/내의판매
              의류/단체복
             의류/맞춤복점
            의류/스포츠의류
             의류/아동의류
            의류/잡화/안경
               의류/정장
                의류관련
            의류관련(기타)
              의류관련기타
               의약품판매
                  의원
             의원/치과의원
              의원/한의원
                 이발소
               이비인후과
                  이사
            이사/화물운송업
                 이용원
               인삼전문점
              인터넷상거래
              인테리어전문
        일반/휴게음식/서양음식
          일반/휴게음식/스넥
        일반/휴게음식/일반한식
       일반/휴게음식/일식·회집
         일반/휴게음식/제과점
          일반/휴게음식/주점
         일반/휴게음식/중국식
                일반가구
                일반병원
               일반상품권
                일반서적
           일반유통/슈퍼마켓
            일반유통/편의점
               일반음식점
                일반의류
                일반주점
             일반치과한의원
                일반한식
         일반휴게음식/서양음식
           일반휴게음식/스넥
        일반휴게음식/위탁급식업
         일반휴게음식/일반한식
        일반휴게음식/일식?회집
         일반휴게음식/일식회집
           일반휴게음식/주점
          일반휴게음식/중국식
         일반휴게음식/칵테일바
               일식·회집
               일식전문점
           입시학원,보습학원
                 자동차
           자동차(국산신차)
           자동차(수입신차)
            자동차(중고차)
             자동차/자전거
             자동차국산신차
               자동차부품
             자동차수입신차
           자동차시트·타이어
             자동차운전학원
               자동차정비
      자동차정비/유지/자동차부품
    자동차정비유지/가타자동차서비스
         자동차정비유지/세차장
     자동차정비유지/윤활유전문판매
       자동차정비유지/자동차부품
   자동차정비유지/자동차시트?타이어
    자동차정비유지/자동차시트타이어
       자동차정비유지/자동차정비
         자동차정비유지/주차장
       자동차정비유지/카인테리어
              자동차중고차
         자동차판매/이륜차판매
       자동차판매/중고자동차판매
                 자전거
            저업소/헬스클럽
           전기제품/가전제품
         전기제품/기타전기제품
           전기제품/냉열기기
            전문스포츠용품점
                 점술업
               정기간행물
              정수기.비데
                  정장
                정형외과
               제과.제빵
                 제과점
        제약회사/의약품도매업체
                 제조업
                  제화
                조명기구
             조명기구.전기
              종합레저타운
                종합병원
                종합용역
               주류전문점
               주류판매점
                주방용구
            주방용구/정수기
          주방용구/주방용식기
                 주유소
            주유소(LPG)
              주유소LPG
                  주점
                 주차장
             주차장.폐차장
              중고품판매점
                 중국식
               중식전문점
             직물/기타직물
            직물/옷감?직물
             직물/옷감직물
           직물/침구?수예점
       직물/침구류/침구·수예점
            직물/침구수예점
     직물/카페트,커튼,천막,지물
            직물/혼수전문점
             차량견인서비스
             차량부품.용품
                차량임대
           차량임대(렌터카)
             차량임대렌터가
             차량임대렌터카
        차량임대렌터카/차량임대
        차량정비/부품/인테리어
               창고보관업
            철재,사무용가구
               체인스토어
              초중고등학교
             축산물,정육점
          축자재/인테리어전문
              출판및인쇄물
                  치과
                치과병원
                치과의원
               치킨전문점
              침구및수예품
             카메라.캠코더
               카인테리어
                칵테일바
            커튼.카펫.수건
            커피/음료전문점
               커피전문점
           컴퓨터및소프트웨어
          컴퓨터및통신기기수리
              타이어판매점
               택배서비스
                  택시
                테니스장
             통신.방문판매
                통신기기
          통업영리/기타유통업
                  티켓
           판촉물.인쇄.복사
               패스트푸드
              패스트푸드점
                 편의점
            피부.체형미관리
                 피부과
               피부미용실
               피부미용원
                  학원
             학원/기능학원
           학원/기타교육기관
              학원/독서실
             학원/보습학원
          학원/예?체능계학원
          학원/예·체능계학원
           학원/예체능계학원
            학원/외국어학원
              학원/유아원
            학원/컴퓨터학원
            학원/학습지교육
              한국인삼공사
                한방병원
                 한복점
                 한약방
                 한의원
                헬스클럽
                  호텔
              호텔(특급)
             호텔(특급외)
               호텔특급외
               혼례서비스
                홍삼제품
                  화랑
                화물운송
              화방.표구점
              화방·표구점
               화원.화초
                 화장품
          회원제형태/건강식품
           회원제형태/기타1
           회원제형태/기타3
           회원제형태/기타4
          회원제형태/레져업소
            회원제형태/서적
            회원제형태/학원

In [22]:
# 팀 분류 결과가 반영된 엑셀 파일을 노트북과 같은 폴더에 저장하세요.
mapping_file = "지역화폐_가맹점_업종대분류_기준표_팀분류반영.xlsx"
industry_map = pd.read_excel(mapping_file, sheet_name="업종매핑")
cols = ["업종명_정리", "대분류", "분류상태"]
industry_map = industry_map[cols]

# 분류표 자체의 중복과 허용되지 않은 분류값을 확인합니다.
if not industry_map["업종명_정리"].is_unique:
    duplicated_names = industry_map.loc[
        industry_map["업종명_정리"].duplicated(keep=False),
        "업종명_정리"
    ].sort_values()
    display(duplicated_names)
    raise ValueError("분류표의 업종명_정리에 중복이 있습니다.")

category_order = [
    "소매", "숙박", "음식", "부동산", "과학·기술", "시설관리·임대",
    "교육", "보건의료", "예술·스포츠", "수리·개인", "기타"
]

unexpected_categories = sorted(
    set(industry_map["대분류"].dropna()) - set(category_order)
)
if unexpected_categories:
    raise ValueError(f"분류표에 허용되지 않은 대분류가 있습니다: {unexpected_categories}")


def clean_industry(value):
    if pd.isna(value):
        return pd.NA

    name = "".join(str(value).split())

    for i, char in enumerate(name):
        if char == "/" and name[:i] == name[i + 1:]:
            return name[:i]

    return name


# 공통 행정동으로 제한했던 store를 사용합니다. 원본 store는 보존합니다.
store_classified = store.drop(
    columns=["대분류", "분류상태"], errors="ignore"
).copy()

store_classified["업종명_정리"] = (
    store_classified["업종명(종목명)"].apply(clean_industry)
)

store_classified = store_classified.merge(
    industry_map,
    on="업종명_정리",
    how="left",
    validate="many_to_one"
)

unmapped = store_classified["대분류"].isna()

if unmapped.any():
    display(
        store_classified.loc[
            unmapped, ["업종명(종목명)", "업종명_정리"]
        ].drop_duplicates()
    )
    raise ValueError(
        "분류표에 없는 업종 또는 업종명 결측이 있습니다. 먼저 확인하세요."
    )

store_classified["개수"] = pd.to_numeric(
    store_classified["개수"], errors="raise"
)

assert store_classified[["년도", "행정동코드", "개수"]].notna().all().all()
assert (store_classified["개수"] >= 0).all()
assert (store_classified["개수"] % 1 == 0).all()

# 연도별·대분류별 실제 지역화폐 가맹점 수를 확인합니다.
category_counts = (
    store_classified.groupby(["년도", "대분류"])["개수"]
    .sum()
    .unstack(fill_value=0)
    .reindex(columns=category_order, fill_value=0)
)
display(category_counts)

# 10개 대분류와 기타를 각각 하나의 열로 집계합니다.
store_wide_major = store_classified.pivot_table(
    index=["년도", "행정동코드"],
    columns="대분류",
    values="개수",
    aggfunc="sum",
    fill_value=0,
    observed=True
).reindex(columns=category_order, fill_value=0)

# 연도·행정동별 집계 전후 총 가맹점 수가 같은지 확인합니다.
before = (
    store_classified.groupby(["년도", "행정동코드"])["개수"]
    .sum()
    .sort_index()
)
after = store_wide_major.sum(axis=1).sort_index()

assert before.index.equals(after.index)
assert (before.to_numpy() == after.to_numpy()).all()

store_wide_major = store_wide_major.add_prefix("가맹점수_").reset_index()
store_wide_major.columns.name = None

# 기존 세부 업종 열을 제거한 사본에 새 11개 분류 열을 붙입니다.
old_store_cols = [
    c for c in merged_df.columns
    if c.startswith("점포수_") or c.startswith("가맹점수_")
]

base = merged_df.drop(columns=old_store_cols).copy()
base["년도"] = base["기준년월"].astype("Int64") // 100

merged_df_major = base.merge(
    store_wide_major,
    on=["년도", "행정동코드"],
    how="left",
    validate="many_to_one",
    indicator="가맹점병합확인"
)

not_matched = ~merged_df_major["가맹점병합확인"].eq("both")
if not_matched.any():
    display(
        merged_df_major.loc[
            not_matched, ["년도", "행정동코드", "가맹점병합확인"]
        ].drop_duplicates()
    )
    raise ValueError("가맹점 자료와 연결되지 않은 연도·행정동이 있습니다.")

merged_df_major = merged_df_major.drop(columns="가맹점병합확인")

assert len(merged_df_major) == len(merged_df)
assert not merged_df_major.duplicated(["기준년월", "행정동코드"]).any()

print("대분류 병합 후 행·열:", merged_df_major.shape)
display(merged_df_major.head())

대분류      소매   숙박     음식  부동산  과학·기술  시설관리·임대     교육  보건의료  예술·스포츠  수리·개인    기타
년도
2023  62089  800  67706  216   2129      788  12633  5957    8851  26477  5185
2024  52666  784  66989  194   2770      679  22254  6516    8546  25558  5840
2025  50165  697  64453  187   2029      723  22080  6128    8422  25304  5410

대분류 병합 후 행·열: (6240, 19)

,기준년월,행정동코드,매출금액,활성화비율,행정구역,총인구수,월유동인구수,년도,가맹점수_소매,가맹점수_숙박,가맹점수_음식,가맹점수_부동산,가맹점수_과학·기술,가맹점수_시설관리·임대,가맹점수_교육,가맹점수_보건의료,가맹점수_예술·스포츠,가맹점수_수리·개인,가맹점수_기타
0,202307,4111156000,41128684.0,100.0,경기도 수원시 장안구 파장동,22480.0,241011.94,2023,274,3,248,1,6,4,14,21,25,97,19
1,202308,4111156000,5115679.0,100.0,경기도 수원시 장안구 파장동,22451.0,241268.02,2023,274,3,248,1,6,4,14,21,25,97,19
2,202309,4111156000,436318.0,100.0,경기도 수원시 장안구 파장동,22410.0,236580.40,2023,274,3,248,1,6,4,14,21,25,97,19
3,202310,4111156000,631469.0,100.0,경기도 수원시 장안구 파장동,23628.0,268762.16,2023,274,3,248,1,6,4,14,21,25,97,19
4,202311,4111156000,591386.0,100.0,경기도 수원시 장안구 파장동,24542.0,253510.66,2023,274,3,248,1,6,4,14,21,25,97,19

In [24]:
save_path = "지역화폐_월별_업종대분류.csv"

merged_df_major.to_csv(
    save_path,
    index=False,
    encoding="utf-8-sig"
)

print("저장 경로:", save_path)
print("저장 행·열:", merged_df_major.shape)

저장 경로: 지역화폐_월별_업종대분류.csv
저장 행·열: (6240, 19)